CREATE DATABASE ristorante_team2
CREATE TABLE menu(
id INT PRIMARY KEY AUTO_INCREMENT,
portata_list VARCHAR(100000) NOT NULL,
tipo_enum VARCHAR(50) NOT NULL,
data_creazione DATETIME NOT NULL
);
CREATE TABLE ristorante.primo(
id INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR NOT NULL,
prezzo DOUBLE NOT NULL,
allergeniEnumArrayList LONG VARCHAR,
calorieEnum LONG VARCHAR NOT NULL,
id_menu FOREIGN KEY
);